[package]
name = "flinch-core"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "stream"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
rusqlite = { version = "0.31", features = ["bundled"] }
tracing = "0.1"
futures-core = "0.3"
async-trait = "0.1"
futures-util = "0.3"
rand = "0.8"
async-stream = "0.3"
command-group = { version = "5", features = ["with-tokio"] }
tempfile = "3"
ts-rs = "12.0.1"
uuid = { version = "1.27.0", features = ["v4"] }
