// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttemptRecord } from "./AttemptRecord";

export type AgentResult = { success: boolean, attempts: Array<AttemptRecord>, };
