// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HarnessResult } from "./HarnessResult";

export type AttemptRecord = { prompt: string, raw_response: string, script: string, harness_result: HarnessResult | null, };
