// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CountsStat = { mesh: number, light: number, camera: number, grease_pencil: number, };
