// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckDetail } from "./CheckDetail";
import type { ErrorDetail } from "./ErrorDetail";
import type { SceneStats } from "./SceneStats";

export type HarnessResult = { schema: number, ok: boolean, stage: string, error: ErrorDetail | null, stdout: string, warnings: Array<string>, scene_stats: SceneStats, checks: Array<CheckDetail>, duration_ms: number, };
