// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CountsStat } from "./CountsStat";
import type { ObjectStat } from "./ObjectStat";

export type SceneStats = { blender_version: string, objects: Array<ObjectStat>, counts: CountsStat, frame_range: [number, number], fps: number, keyframe_count: number, };
